<<<<<<< HEAD
=======

development:
  adapter: postgresql
  database: hitchens
  pool: 5
  host: localhost
>>>>>>> send_method

development:
    adapter: postgresql
    encoding: unicode
    database: hitchens_development
    host: localhost
    pool: 5
    username: styxut
    password:             
                 
test:
    adapter: postgresql
<<<<<<< HEAD
    encoding: unicode
    database: hitchens_test
    host: localhost
    pool: 5
    username: styxut
    password:   

production:
    adapter: postgresql
    encoding: unicode
    database: hitchens_production
    pool: 5
    username: styxut
    password:   
=======
    database: test_hitchens
    pool: 5
    host: localhost

production:
    adapter: postgresql
    database: hitchens
    pool: 5
    host: localhost
>>>>>>> send_method
