

development:
  adapter: postgis
  schema_search_path: 'public,postgis'  
  script_dir: '/Applications/Postgres.app/Contents/MacOS/share/contrib/postgis-2.0/'
  postgis_extension: true
  encoding: unicode
  database: hitchens_development
  host: localhost  
  pool: 5
  username: styxut
  password:      
                 
test:
    adapter: postgis
    schema_search_path: 'public,postgis'  
    script_dir: '/Applications/Postgres.app/Contents/MacOS/share/contrib/postgis-2.0/'
    postgis_extension: true
    encoding: unicode
    database: hitchens_test
    host: localhost  
    pool: 5
    username: styxut
    password: 

production:
    adapter: postgis
    schema_search_path: 'public,postgis'  
    script_dir: '/Applications/Postgres.app/Contents/MacOS/share/contrib/postgis-2.0/'
    postgis_extension: true
    encoding: unicode
    database: hitchens
    host: localhost  
    pool: 5
    username: styxut
    password:   

