
development:
    adapter: postgresql
    encoding: unicode
    database: hitchens_development
    host: localhost
    pool: 5
    username: styxut
    password:             
                 
test:
    adapter: postgresql
    encoding: unicode
    database: hitchens_test
    host: localhost
    pool: 5
    username: styxut
    password:   

production:
    adapter: postgresql
    encoding: unicode
    database: hitchens_production
    pool: 5
    username: styxut
    password:   